name: Tests

on:
  push:
    branches: [ 'main', 'versions/*' ]
  pull_request:
    branches: [ 'main', 'versions/*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ] # node.js LTS versions - see https://endoflife.date/nodejs

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install also Cypress binaries (they are not cached)
        run: npx cypress install --force
      - name: Execute tests
        run: pnpm test
