name: Tests

on:
  push:
    branches: [ 'main', 'versions/*' ]
  pull_request:
    branches: [ 'main', 'versions/*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ] # node.js LTS versions - see https://endoflife.date/nodejs

    steps:
      - uses: actions/checkout@latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@latest
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
